package org.vergen.generator;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

class GeneratorTest {
	
	static String expectedContentResultFile;

	@BeforeAll
	public static void beforeAll() {

		setContentResultFile();
	}

	@Test
	void renderTest() {
		
		String resultFileName = "D:\\PacConfigVersion.hpp";
		
		Generator generator = new Generator("D:\\git\\vergen\\jinja\\PacConfigVersion.jinja", resultFileName);
		
		generator.setMajor(1);
    	generator.setMinor(64);
    	generator.setBugfix(5);
    	generator.setBuild(9);
    	
    	generator.render();
    	
    	try
    	{
    		String contentResultFile = new String(Files.readAllBytes(Paths.get(resultFileName)));
    		assertTrue(contentResultFile.equals(expectedContentResultFile));
    		
    	} catch (IOException e) {
			e.printStackTrace();
		}
    	
		
		assertEquals(4, 4);
		
	}

	private static void setContentResultFile() {

		expectedContentResultFile = "/**" + System.lineSeparator() + "* file generated by vergen" + System.lineSeparator() + "**/   " + System.lineSeparator() + System.lineSeparator()
				+ "#ifndef __INC_PacConfigVersionHPP" + System.lineSeparator() + "#define __INC_PacConfigVersionHPP" + System.lineSeparator() + System.lineSeparator()
				+ "const char FW_VERSION_3S_STRING[9]  = \"1.64.5.9\";" + System.lineSeparator() + System.lineSeparator()
				+ "const UINT8 FW_VERSION_MAJOR  = 1;" + System.lineSeparator() + "const UINT8 FW_VERSION_MINOR  = 64;" + System.lineSeparator()
				+ "const UINT8 FW_VERSION_BUGFIX = 5;" + System.lineSeparator() + "const UINT8 FW_VERSION_BUILD  = 9;" + System.lineSeparator() + System.lineSeparator()
				+ "const UINT32 FW_VERSION_UINT32 = 0x01400509;" + System.lineSeparator() + System.lineSeparator()
				+ "const char FW_VERSION_STRING[13]  = \"V01.64.05.09\";" + System.lineSeparator()
				+ "const int FW_VERSION_STRING_LENGTH  = 13;" + System.lineSeparator() + System.lineSeparator()
				+ "const char FW_VERSION_STRING_USER[8]  = \"V1.64.5\";" + System.lineSeparator()
				+ "const int FW_VERSION_STRING_USER_LENGTH  = 8;" + System.lineSeparator() + System.lineSeparator()
				+ "const char FW_VERSION_STRING_COMPLETE[10]  = \"V1.64.5.9\";" + System.lineSeparator()
				+ "const int FW_VERSION_STRING_COMPLETE_LENGTH  = 10;" + System.lineSeparator() + System.lineSeparator() + "#ifdef FILE_PacDriveCPP" + System.lineSeparator()
				+ "   int g_lMax4VersionIdStart016405End;" + System.lineSeparator() + "   int g_lMax4Version2IdStart01_64_05_09End;" + System.lineSeparator()
				+ "#endif" + System.lineSeparator() + System.lineSeparator() + "#endif //__INC_PacConfigVersionHPP" + System.lineSeparator();
	}

}
