package org.vergen.generator;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

class GeneratorTest {
	
	static String contentResultFile;

	@BeforeAll
	public static void beforeAll() {

		setContentResultFile();
	}

	@Test
	void renderTest() {
		
		Generator generator = new Generator("D:\\git\\vergen\\jinja\\PacConfigVersion.jinja", "D:\\PacConfigVersion.hpp");
		
		generator.setMajor(1);
    	generator.setMinor(64);
    	generator.setBugfix(5);
    	generator.setBuild(9);
    	
    	generator.render();
		
		assertEquals(4, 4);
		
	}

	private static void setContentResultFile() {

		contentResultFile = "/**\n" + "* file generated by vergen\n" + "**/   \n" + "\n"
				+ "#ifndef __INC_PacConfigVersionHPP\n" + "#define __INC_PacConfigVersionHPP\n" + "\n"
				+ "const char FW_VERSION_3S_STRING[9]  = \"1.64.5.9\";\n" + "\n"
				+ "const UINT8 FW_VERSION_MAJOR  = 1;\n" + "const UINT8 FW_VERSION_MINOR  = 64;\n"
				+ "const UINT8 FW_VERSION_BUGFIX = 5;\n" + "const UINT8 FW_VERSION_BUILD  = 9;\n" + "\n"
				+ "const UINT32 FW_VERSION_UINT32 = 0x01400509;;\n" + "\n"
				+ "const char FW_VERSION_STRING[13]  = \"V01.64.05.09\";\n"
				+ "const int FW_VERSION_STRING_LENGTH  = 13;\n" + "\n"
				+ "const char FW_VERSION_STRING_USER[8]  = \"V1.64.5\";\n"
				+ "const int FW_VERSION_STRING_USER_LENGTH  = 8;\n" + "\n"
				+ "const char FW_VERSION_STRING_COMPLETE[10]  = \"V1.64.5.9\";\n"
				+ "const int FW_VERSION_STRING_COMPLETE_LENGTH  = 10;\n" + "\n" + "#ifdef FILE_PacDriveCPP\n"
				+ "   int g_lMax4VersionIdStart016404End;\n" + "   int g_lMax4Version2IdStart01_64_05_09End;\n"
				+ "#endif\n" + "\n" + "#endif //__INC_PacConfigVersionHPP";
	}

}
