package generator;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;

class GeneratorTest {

	private static String pacConfigVersionStandardValue;
	private static final String TEMPLATE_FILE = "src/test/resources/PacConfigVersion.jinja";
	private static final String GENERATE_FILE = "src/test/resources/PacConfigVersion.hpp";

	@BeforeAll
	public static void beforeAll() {
		try {
			Path path = Paths.get(GENERATE_FILE);
			if (Files.exists(path)) {
				Files.delete(path);
			}
		} catch (IOException e) {
			assertTrue(false);
		}

		setPacConfigVersionStandardValue();
	}

	@Test
	void generateTest() {
		try {
			Version version = new Version();
			version.set(1, 64, 5, 4);

			Generator generatorPacDrive = new Generator(TEMPLATE_FILE, version);

			generatorPacDrive.generate(GENERATE_FILE);

			Path path = Paths.get(GENERATE_FILE);
			String pacConfigVersionGenerated = new String(Files.readAllBytes(path));

			assertTrue(pacConfigVersionStandardValue.equals(pacConfigVersionGenerated));
		}

		catch (VersionException e) {
			assertTrue(false);
		}
		
		catch (IOException e) {
			assertTrue(false);
		}

	}

	private static void setPacConfigVersionStandardValue() {

		pacConfigVersionStandardValue = "/**\n" + "* file generated by vergen\n" + "**/   \n" + "\n"
				+ "#ifndef __INC_PacConfigVersionHPP\n" + "#define __INC_PacConfigVersionHPP\n" + "\n"
				+ "const char FW_VERSION_3S_STRING[9]  = \"1.64.5.4\";\n" + "\n"
				+ "const UINT8 FW_VERSION_MAJOR  = 1;\n" + "const UINT8 FW_VERSION_MINOR  = 64;\n"
				+ "const UINT8 FW_VERSION_BUGFIX = 5;\n" + "const UINT8 FW_VERSION_BUILD  = 4;\n" + "\n"
				+ "const UINT32 FW_VERSION_UINT32 = 0x01400504;;\n" + "\n"
				+ "const char FW_VERSION_STRING[13]  = \"V01.64.05.04\";\n"
				+ "const int FW_VERSION_STRING_LENGTH  = 13;\n" + "\n"
				+ "const char FW_VERSION_STRING_USER[8]  = \"V1.64.5\";\n"
				+ "const int FW_VERSION_STRING_USER_LENGTH  = 8;\n" + "\n"
				+ "const char FW_VERSION_STRING_COMPLETE[10]  = \"V1.64.5.4\";\n"
				+ "const int FW_VERSION_STRING_COMPLETE_LENGTH  = 10;\n" + "\n" + "#ifdef FILE_PacDriveCPP\n"
				+ "   int g_lMax4VersionIdStart016405End;\n" + "   int g_lMax4Version2IdStart01_64_05_04End;\n"
				+ "#endif\n" + "\n" + "#endif //__INC_PacConfigVersionHPP\n";
	}

}
